@echo off
echo Installing Node.js dependencies...
call npm install

echo Updating HTML files...
node update_html.js

echo Setting up assets and Font Awesome...
node copy-assets.js

echo Starting Electron app...
npm start